version: "3.8"

services:
  test:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: devChallengeTest
    working_dir: /root/workdir
    volumes:
      - ./:/root/workdir
      - maven:/root/.m2
    entrypoint: mvn test

volumes:
  maven:
